module.exports = {
	FETCH_SONGS_REQEUST: 'FETCH_SONGS_REQEUST',
	FETCH_SONGS_SUCESS: 'FETCH_SONGS_SUCESS',
	FETCH_SONGS_FAILURE: 'FETCH_SONGS_FAILURE',

	ADD_NEW_SONG: 'ADD_NEW_SONG',
	UPDATE_SONG_SUCESS: 'UPDATE_SONG_SUCESS',
	DELETE_SONG: 'DELETE_SONG'
};