module.exports = {
	FETCH_SONGS_REQEUST: 'FETCH_SONGS_REQEUST',
	FETCH_SONGS_SUCESS: 'FETCH_SONGS_SUCESS',
	FETCH_SONGS_FAILURE: 'FETCH_SONGS_FAILURE',

	ADD_NEW_SONG: 'ADD_NEW_SONG',
	UPDATE_SONG_SUCESS: 'UPDATE_SONG_SUCESS',
	DELETE_SONG: 'DELETE_SONG',

	FETCH_SINGERS_SUCESS: 'FETCH_SINGERS_SUCESS',
	ADD_NEW_SINGER: 'ADD_NEW_SINGER',
	UPDATE_SINGER_SUCESS: 'UPDATE_SINGER_SUCESS',
	DELETE_SINGER: 'DELETE_SINGER'
};